version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    environment:
      - TF_ENABLE_ONEDNN_OPTS=0
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
